#pragma once

#include <cstdint>

namespace audioapi {

enum class AudioEvent : uint8_t {
  PLAYBACK_NOTIFICATION_PLAY,
  PLAYBACK_NOTIFICATION_PAUSE,
  PLAYBACK_NOTIFICATION_STOP,
  PLAYBACK_NOTIFICATION_NEXT_TRACK,
  PLAYBACK_NOTIFICATION_PREVIOUS_TRACK,
  PLAYBACK_NOTIFICATION_SKIP_FORWARD,
  PLAYBACK_NOTIFICATION_SKIP_BACKWARD,
  PLAYBACK_NOTIFICATION_SEEK_FORWARD,
  PLAYBACK_NOTIFICATION_SEEK_BACKWARD,
  PLAYBACK_NOTIFICATION_SEEK_TO,
  PLAYBACK_NOTIFICATION_DISMISSED,
  RECORDING_NOTIFICATION_RESUME,
  RECORDING_NOTIFICATION_PAUSE,
  ROUTE_CHANGE,
  INTERRUPTION,
  VOLUME_CHANGE,
  DUCK,
  ENDED,
  LOOP_ENDED,
  AUDIO_READY,
  POSITION_CHANGED,
  BUFFER_ENDED,
  RECORDER_ERROR,
};
} // namespace audioapi
