name: CI
on:
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested

jobs:
  format-check:
    uses: ./.github/workflows/ci-check.yml
    with:
      name: Format check
      run: yarn format:check

  lint:
    uses: ./.github/workflows/ci-check.yml
    with:
      name: Lint and typecheck
      run: |
        yarn lint
        yarn typecheck

  check-audio-enum-sync:
    uses: ./.github/workflows/ci-check.yml
    with:
      name: Check AudioEvent enum sync
      run: yarn check-audio-enum-sync

  build-library:
    uses: ./.github/workflows/ci-check.yml
    with:
      name: Build package
      run: yarn build
